### PR TITLE
stake all option; set max amount of tries for each wallet

### PR DESCRIPTION
**Pull request by kartashovio**
I plan to deposit from exchange a random amount of Jup to the solana network. Convenient ability to stake the entire balance

### CODE REVIEW

**Comment by kartashovio** [comment]
@okeyzero check code pls, I'm not an expert

**Comment by kartashovio** [comment]
but i tested my code for 1 wallet, it works ok

**Comment by kartashovio** [comment]
@okeyzero i also added code for max amount of tries for each wallet. Its necessary for https://github.com/okeyzero/jupStaker_SOL/issues/3

**Comment by okeyzero** [comment]
Thank you. I'll take care of it as soon as I can.

**Pull request merged**
